# SPDX-License-Identifier: Apache-2.0

name: HOL-Light
permissions:
  contents: read
on:
  push:
    branches: ["main"]
    # Only run upon changes to AArch64 NTT or invNTT
    paths:
     - 'proofs/hol_light/arm/**/*.S'
     - 'proofs/hol_light/arm/**/*.ml'
  pull_request:
    branches: ["main"]
    paths:
      # Only run upon changes to AArch64 NTT or invNTT
      - 'proofs/hol_light/arm/**/*.S'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  hol_light_proofs:
    strategy:
      matrix:
        proof: [mlkem_ntt,mlkem_intt,keccak_f1600_x1_scalar,keccak_f1600_x1_v84a,keccak_f1600_x2_v84a]
    name: HOL Light proof for ${{ matrix.proof }}.S
    runs-on: pqcp-arm64
    if: github.repository_owner == 'pq-code-package' && !github.event.pull_request.head.repo.fork
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@dcc7a0cba800f454d79fff4b993e8c3555bcc0a8 # v45.0.7
      - uses: ./.github/actions/setup-shell
        if: |
          contains(steps.changed-files.outputs.all_changed_files,format('{0}.S',matrix.proof)) ||
          contains(steps.changed-files.outputs.all_changed_files,format('{0}.ml',matrix.proof))
        with:
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          nix-shell: 'hol_light'
          script: |
            make -C proofs/hol_light/arm mlkem/${{ matrix.proof }}.correct
